---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
root_url <- "https://charlotte-ngs.github.io/lbgfs2023" 
```

Additional material for LBGFS2023

# Slides

```{r slide-table, echo=FALSE, message=FALSE, warning=FALSE}
sl_url <- paste0(root_url, "/sl/")
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                         Date = c("2023-09-22",
                                  "2023-09-29",
                                  "2023-10-06",
                                  "2023-10-13",
                                  "2023-10-13",
                                  "2023-10-20",
                                  "2023-10-27",
                                  "2023-11-10"),
                         Topic = c(
                           paste0("[Introduction to Livestock Breeding and Genomics](", 
                                  sl_url, 
                                  "lbgfs2023_slides_l01_intro_lbg.pdf)", 
                                  collapse = ""),
                           paste0("[Basics of Quantitative Genetics](", 
                                  sl_url, 
                                  "lbgfs2023_slides_l02_basics_qg.pdf)", 
                                  collapse = ""),
                           paste0("[Multiple Loci](",
                                  sl_url,
                                  "l03_qg_multiple_loci.pdf)", 
                                  collapse = ""),
                           paste0("[Alternative Explanation of Breeding Values](",
                                  sl_url,
                                  "l04_alt_expl_bv.pdf)",
                                  collapse = ""),
                           paste0("[Genetic Evaluation](",
                                  sl_url,
                                  "l04_gen-eval.pdf)",
                                  collapse = ""),
                           paste0("[Parent Offspring Breeding Values](",
                                  sl_url,
                                  "l05_parent_offspring_bv.pdf)", 
                                  collapse = ""),
                           paste0("[BLUP](",
                                  sl_url,
                                  "l06_blup.pdf)",
                                  collapse = ""),
                           paste0("[Genetic Covariance between Animals](",
                                  sl_url,
                                  "l07_gen_cov.pdf)",
                                  collapse = "")
                           ))
knitr::kable(tbl_sl)
```


# Handouts

```{r hand-outs-table, echo=FALSE, message=FALSE, warning=FALSE}
s_ho_url <- file.path(root_url,"houts")
tbl_ho <- tibble::tibble(Nr = c(1),
                         Date = c("2023-09-22"),
                         Topic = c(
                           paste0("JypyterHub Platform [html](",
                                  s_ho_url, 
                                  "/20230921_howto_jhub.html) | [pdf](",
                                  s_ho_url,
                                  "/20230921_howto_jhub.pdf)")
                         ))
knitr::kable(tbl_ho)
```


# Datasets

```{r data-set-table, echo=FALSE, message=FALSE, warning=FALSE}
s_data_url <- file.path(root_url, "data")
tbl_data <- tibble::tibble(Nr = c(1, 2, 3),
                           Date = c("2023-09-29",
                                    "2023-10-13",
                                    "2023-10-27"),
                           Topic = c(
                             paste0("[Exercise 3 - Problem 1](",
                                    file.path(s_data_url, 
                                    "lbgfs2023_lbg_ex03.csv)"),
                                    collapse = ""),
                             paste0("[Exercise 5](",
                                    file.path(s_data_url,
                                    "p1_qtl_1_loci.csv)"),
                                    collapse = ""),
                             paste0("[Beef Cattle Data](",
                                    file.path(s_data_url,
                                    "beef_data_blup.csv)"),
                                    collapse = "")
                           ))
knitr::kable(tbl_data)
```


## Overhead Pictures

```{r ohp-table, echo=FALSE, message=FALSE, warning=FALSE}
s_ohp_url <- file.path(root_url, "ohp")
tbl_ohp <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7),
                          Date = c("2023-09-22",
                                   "2023-09-29",
                                   "2023-10-06",
                                   "2023-10-13",
                                   "2023-10-20",
                                   "2023-10-27",
                                   "2023-11-03"),
                          Topic = c(
                            paste0("[Introduction](",
                                   s_ohp_url,
                                   "/20230922_ohp_l01.pdf)", collapse = ""),
                            paste0("[Frequencies and Values](",
                                   s_ohp_url,
                                   "/20230929_ohp_l02.pdf)", collapse = ""),
                            paste0("[Breeding Values](",
                                   s_ohp_url,
                                   "/20231006_ohp_l03.pdf)", collapse = ""),
                            paste0("[Many Loci](", 
                                   s_ohp_url, 
                                   "/20231013_ohp_l04.pdf)", collapse = ""),
                            paste0("[Genetic Evaluation](",
                                   s_ohp_url,
                                   "/20231020_ohp_l05.pdf)", collapse = ""),
                            paste0("[BLUP](",
                                   file.path(s_ohp_url, "20231027_ohp_l06.pdf"), 
                                   ")",
                                   collapse = ""),
                            paste0("[Mixed Models](",
                                   file.path(s_ohp_url,"20231103_ohp_l07.pdf"),
                                   ")",
                                   collapse = "")
                          ))
knitr::kable(tbl_ohp)
```



```{r latest-changes, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
cat(paste0("\n---\n\n", 
           " _Latest Changes: ", 
           format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), 
           " (", 
           Sys.info()[["user"]], 
           ")_", collapse = ""))
```




