---
title: "Exercises"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exercises}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Links to exercises are shown in the following table.

```{r exercise-table, echo=FALSE, message=FALSE, warning=FALSE}
s_ex_url <- "https://charlotte-ngs.github.io/lbgfs2023/ex/"
s_nb_url <- "https://charlotte-ngs.github.io/lbgfs2023/nb/"
tbl_ex <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                         Date = c("2023-09-22",
                                  "2023-09-29",
                                  "2023-09-29",
                                  "2023-10-06",
                                  "2023-10-13",
                                  "2023-10-20",
                                  "2023-10-27",
                                  "2023-11-03"),
                         Topic = c(
                           paste0("[Questionnaire](", 
                                  s_ex_url, 
                                  "lbg_ex01.pdf)", collapse = ""),
                           paste0("Linear Algebra [pdf](", 
                                  s_ex_url, 
                                  "lbg_ex02.pdf) | [nb](", 
                                  s_nb_url, 
                                  "lbg_ex02_nb_src.nb.html)", collapse = ""),
                           paste0("Hardy-Weinberg Equilibrium [pdf](",
                                  s_ex_url,
                                  "lbg_ex03.pdf) | [nb](",
                                  s_nb_url,
                                  "lbg_ex03_nb_src.nb.html)", collapse = ""),
                           paste0("Breeding Values [pdf](",
                                  s_ex_url,
                                  "lbg_ex04.pdf) | [nb](",
                                  s_nb_url,
                                  "lbg_ex04_nb_src.nb.html)", collapse = ""),
                           paste0("Genetic Evaluation [pdf](",
                                  s_ex_url,
                                  "lbg_ex05.pdf) | [nb](",
                                  s_nb_url,
                                  "lbg_ex05_nb_src.nb.html)", collapse = ""),
                           paste0("Parent Offspring Breeding Values [pdf](",
                                  s_ex_url,
                                  "lbg_ex06.pdf) | [nb](",
                                  s_nb_url,
                                  "lbg_ex06_nb_src.nb.html)", collapse = ""),
                           paste0("Own Performance, Repeated Records and Progeny Records [pdf](",
                                  s_ex_url,
                                  "lbg_ex07.pdf) | [nb](",
                                  s_nb_url, 
                                  "lbg_ex07_nb_src.nb.html)", collapse = ""),
                           paste0("Linear Models [pdf](",
                                  s_ex_url,
                                  "lbg_ex08.pdf) | [nb](",
                                  s_nb_url,
                                  "lbg_ex08_nb_src.nb.html)", collapse = "")
                           ))
knitr::kable(tbl_ex)
```


```{r latest-changes, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
cat(paste0("\n---\n\n", 
           " _Latest Changes: ", 
           format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), 
           " (", 
           Sys.info()[["user"]], 
           ")_", collapse = ""))
```


